package edu.pitt.cs;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import static org.hamcrest.MatcherAssert.assertThat;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;
public class PittEduTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(30));
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tEST4SCHOOLSSCI() {
    // Test name: TEST-4-SCHOOLS-SCI
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.pitt.edu/");
    // 2 | setWindowSize | 1211x1012 | 
    driver.manage().window().setSize(new Dimension(1211, 1012));
    // 3 | click | css=.icon-hamburger | 
    driver.findElement(By.cssSelector(".icon-hamburger")).click();
    // 4 | waitForElementVisible | id=block-collegesschools-menu | 30000
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("block-collegesschools-menu")));
    }
    // 5 | assertText | xpath=//div[@id='menu-blockquick-links-3']/ul/li[3]/a | Computing & Information
    assertThat(driver.findElement(By.xpath("//div[@id=\'menu-blockquick-links-3\']/ul/li[3]/a")).getText(), is("Computing & Information"));
  }
  @Test
  public void tEST1TITLE() {
    // Test name: TEST-1-TITLE
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.pitt.edu/");
    // 2 | setWindowSize | 911x1012 | 
    driver.manage().window().setSize(new Dimension(911, 1012));
    // 3 | assertTitle | Home | University of Pittsburgh | 
    assertThat(driver.getTitle(), is("Home | University of Pittsburgh"));
  }
  @Test
  public void tEST2LOGOEXISTS() {
    // Test name: TEST-2-LOGO-EXISTS
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.pitt.edu/");
    // 2 | setWindowSize | 1211x1012 | 
    driver.manage().window().setSize(new Dimension(1211, 1012));
    // 3 | assertElementPresent | xpath=//img[@alt='University of Pittsburgh'] | 
    {
      List<WebElement> elements = driver.findElements(By.xpath("//img[@alt=\'University of Pittsburgh\']"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST3LOGOIMAGE() {
    // Test name: TEST-3-LOGO-IMAGE
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.pitt.edu/");
    // 2 | setWindowSize | 1211x1012 | 
    driver.manage().window().setSize(new Dimension(1211, 1012));
    // 3 | storeAttribute | xpath=//img[@alt='University of Pittsburgh']@src | logo_src
    {
      WebElement element = driver.findElement(By.xpath("//img[@alt=\'University of Pittsburgh\']"));
      String attribute = element.getAttribute("src");
      vars.put("logo_src", attribute);
    }
    // 4 | assert | logo_src | /themes/custom/pitt_default/logo.svg
    assertEquals(vars.get("logo_src").toString(), "https://www.pitt.edu/themes/custom/pitt_default/logo.svg");
  }
  @Test
  public void tEST6SEARCHCSC() {
    // Test name: TEST-6-SEARCH-CSC
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.pitt.edu/");
    // 2 | setWindowSize | 1211x1012 | 
    driver.manage().window().setSize(new Dimension(1211, 1012));
    // 3 | click | css=.icon-search | 
    driver.findElement(By.cssSelector(".icon-search")).click();
    // 4 | click | id=gsc-i-id1 | 
    driver.findElement(By.id("gsc-i-id1")).click();
    // 5 | type | id=gsc-i-id1 | csc
    driver.findElement(By.id("gsc-i-id1")).sendKeys("csc");
    // 6 | sendKeys | id=gsc-i-id1 | ${KEY_ENTER}
    driver.findElement(By.id("gsc-i-id1")).sendKeys(Keys.ENTER);
    // 7 | assertText | xpath=//div[4]/div/div/div/a | Computer Science Club (CSC) | Department of Computer Science ...
    assertThat(driver.findElement(By.xpath("//div[4]/div/div/div/a")).getText(), is("Computer Science Club (CSC) | Department of Computer Science ..."));
  }
  @Test
  public void tEST5SCHOOLSCOUNT() {
    // Test name: TEST-5-SCHOOLS-COUNT
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.pitt.edu/");
    // 2 | setWindowSize | 1211x1012 | 
    driver.manage().window().setSize(new Dimension(1211, 1012));
    // 3 | click | css=.icon-hamburger | 
    driver.findElement(By.cssSelector(".icon-hamburger")).click();
    // 4 | assertElementPresent | xpath=//div/div[2]/div/div/div[2]/div/ul/li[16] | 
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div/div[2]/div/div/div[2]/div/ul/li[16]"));
      assert(elements.size() > 0);
    }
    // 5 | assertElementNotPresent | xpath=//div/div[2]/div/div/div[2]/div/ul/li[17] | 
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div/div[2]/div/div/div[2]/div/ul/li[17]"));
      assert(elements.size() == 0);
    }
  }
}
